// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";
import type { JsonValue } from "../serde_json/JsonValue";
import type { WorkflowWorkspace } from "./WorkflowWorkspace";

export type WorkflowWorkerStartParams = { runId: string, workerId: string, parentThreadId: string, authorityRef: string, authorityGeneration: bigint, authorityDigest: string, prompt: string, model: string, effort: ReasoningEffort, modelExplicit: boolean, effortExplicit: boolean,
/**
 * Native role name. The host resolves configured roles; this protocol does not freeze an enum.
 */
agentType: string, roleDigest: string,
/**
 * Restrict this worker to the parent's read-only intersection.
 */
readOnly: boolean, workspace: WorkflowWorkspace, schema: JsonValue | null, resumeThreadId: string | null, };
