// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowSaveParams = { parentThreadId: string, authorityRef: string, authorityDigest: string, runId: string, name: string, scope: string, source: string, sourceDigest: string, };
