// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Advisory target for the number of agents in a dynamically authored workflow.
 */
export type WorkflowSizeGuideline = "unrestricted" | "small" | "medium" | "large";
