// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";
import type { WorkflowModelOption } from "./WorkflowModelOption";
import type { WorkflowPluginOption } from "./WorkflowPluginOption";

export type WorkflowAuthorityCaptureResponse = { authorityRef: string, generation: bigint, authorityDigest: string, cwd: string, parentModel: string, parentEffort: ReasoningEffort | null, models: Array<WorkflowModelOption>, plugins: Array<WorkflowPluginOption>, webSearchAvailable: boolean,
/**
 * Effective native workflow listener, used to bind a headless controller to its parent.
 */
workflowHostUrl: string | null, };
