// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowWorkspace } from "./WorkflowWorkspace";

export type WorkflowWorkspacePrepareParams = { runId: string, workerId: string, agentType: string, authorityRef: string, authorityDigest: string, isolation: string | null, requestedCwd: string, previous: WorkflowWorkspace | null, };
